### ISSUE TITLE
Notebooks in README moved

### ISSUE THREAD

**Issue by michaelrzhang** [tensorflow/workshops#32]
When you open the notebooks in Colaboratory, they show up as "This file has moved."

**Comment by rajeshwerkushwaha** [comment]
Meanwhile, PR get's approved, use the below links.

[MNIST](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_classification.ipynb)

[IMDB](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_text_classification.ipynb)

[Housing prices](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_regression.ipynb)

[Overfitting vs underfitting](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/overfit_and_underfit.ipynb)

[Text generation](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/sequences/text_generation.ipynb)

[Translation](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb)

**Comment by michaelrzhang** [comment]
PR lgtm, thanks!
